#!/bin/sh

CF_VER=2.11.1

javac \
    \
    -d out \
    src/Test.java \
    -version \
    -verbose \
    -AprintAllQualifiers \
    -g \
    -encoding UTF-8 \
    -AshowSuppressWarningKeys \
    \
    -J-Xbootclasspath/p:../libs/com.google.errorprone/javac-9+181-r4173-1.jar \
    -Xbootclasspath/p:../libs/checkerframework/jdk8-"${CF_VER}".jar \
    -cp ../libs/checkerframework/checker-qual-"${CF_VER}".jar \
    -processorpath ../libs/checkerframework/checker-"${CF_VER}".jar \
    -processor org.checkerframework.checker.nullness.NullnessChecker \
    -source 8 -target 8
