#!/bin/sh
javac -d out -classpath jars/osgi.core-6.0.0.jar:jars/checker-2.1.14.jar src/Test.java -processor org.checkerframework.checker.nullness.NullnessChecker -g -target 1.8 -source 1.8 -encoding UTF-8 -Astubs=stubs -AstubWarnIfNotFound -AstubWarnIfOverwritesBytecode -AstubDebug -AshowSuppressWarningKeys -Xbootclasspath/p:jars/org.checkerframework.jdk8-2.1.14.jar
